### ISSUE TITLE
Permission access camera and file library

### ISSUE THREAD

**Issue by hafiz013** [vinceglb/FileKit#108]
I have seen this library is good but one things is missing here which is run time permission for access camera and file library in kotlin multiplatform. For your information, android 15 permission is already changes as compared to others platform.

**Comment by vinceglb** [comment]
Hi! Thanks for creating this issue.

I'm not sure to understand well your problem. Actually, FileKit doesn't access the camera feature, so it doesn't need camera permission access. Also, to my knowledge, there is no permission needed to open a file picker.

Can you please provide more details about what you mean? Thanks in advance
