### ISSUE TITLE
Android Overwriting a file when saving

### ISSUE THREAD

**Issue by DmitriyHook** [vinceglb/FileKit#117]
Currently on Android, if you select an existing file when saving a file, N bytes will be overwritten in this file, where N is the size of the byte array to save. If the size of the existing file before saving exceeded the size of the array being saved, the file size does not change and incorrect data remains in it. When selecting a file to save, it is important to click on the existing file (so that the existing file is overwritten, and not a copy is created).

On the JVM, everything works correctly and after saving, the file size is equal to the size of the array being saved.

**Comment by santiwanti** [comment]
This is a limitation imposed by the [Google API](https://developer.android.com/training/data-storage/shared/documents-files#create-file). As the note mentions, the api can't overwrite files, it just appends a number to them. We can llook into changing the API we use though.

Regarding the problem with garbage still being in the file I will look into that.

**Comment by santiwanti** [comment]
A PR has been created that fixes the overidding issue, making sure we truncate the file that we are overwriting.

**Comment by santiwanti** [comment]
Fixed in https://github.com/vinceglb/FileKit/pull/119.
