### ISSUE TITLE
IOS: "saveFile" throw an error if called not from main thread

### ISSUE THREAD

**Issue by Monabr** [vinceglb/FileKit#122]
Hello.

I am using this code

```
launch(Dispatchers.IO) {
            FileKit.saveFile(
                baseName = fileName,
                extension = "csv",
                bytes = bites
            )
}
            
```

in my ViewModel.

Android part works fine but iOS drops the error saying this should be called from main thread.

I believe main thread safety is library responsibility.

Since `saveFile` is a suspend function you could easily make it by writing 
```
withContext(Dispatchers.Main) {
...
}
```

**Comment by santiwanti** [comment]
I will look into this now and see if it's as easy as running it in `Dispatchers.Main`

**Comment by vinceglb** [comment]
I'm going to push a fix soon 👌
