### ISSUE TITLE
When swiping bottom sheet in iOS the event not generated

### ISSUE THREAD

**Issue by derynia** [vinceglb/FileKit#127]
I have a following composable function

```kotlin
@Composable
fun PickFile(
    type: String,
    afterPick: (PlatformFile?) -> Unit
) {
    val launcher = rememberFilePickerLauncher(
        type =
        when (type) {
            SELECT_FILE_CLICKED -> PickerType.Image
            SELECT_VIDEO -> PickerType.Video
            else -> PickerType.File(listOf("pdf"))
        },
        mode = PickerMode.Single,
        title = Strings.getString("pic_a_file")
    ) { file -> afterPick(file) }
    launcher.launch()
}
```

in my viemodel I check if the file is selected I'm starting to upload it. If the selection dialog is dismissed I clear the state of viewmodel to unblock the selectButton

```kotlin
private fun startFileUpload(platformFile: PlatformFile?) {
    Napier.i(tag = "FileSelect", message = "Starting upload")
    platformFile?.let {
        uploadFile(
            profileRepo = profileRepo,
            scope = scope,
            platformFile = it,
            type = PROCESSING_DOCUMENTS,
        )
    } ?: errorsShown()
}
```

It works fine in Android. But in iOS if I swipe down file selection dialog insead of pressing Cancel button nothing happens. Event is not generated so the code in viewModel is not called.
Again if I dismiss by pressing Cancel in selection dialog everything works fine.
In Android all ways of dialog dismiss work fine.
The problem exists in both simulator and physical devices on iOS18 and earlier versions.

![Simulator Screenshot - iPhone 14 Pro Max - 2024-10-03 at 18 09 34](https://github.com/user-attachments/assets/14a1a739-fad4-4064-b51d-d51571d3aceb)

**Comment by derynia** [comment]
I also found out that when picking a document, not photo everything works fine.
The problem seems to be in PHPickerViewControllerDelegateProtocol which doesn't have 
`    override fun documentPickerWasCancelled(controller: UIDocumentPickerViewController) {
        onPickerCancelled()
    }
`
as UIDocumentPickerDelegateProtocol does. So it seems to be the problem is in netive iOS component.
Also I googled this problem and found some kind of solution here:
https://forums.developer.apple.com/forums/thread/704315

But I don't understand at all how to implement it as I'm very weak in Swift.

**Comment by vinceglb** [comment]
Hi @derynia! Thanks for reporting this issue! I'm going to take a look.

**Comment by derynia** [comment]
I asked this question on Apple Developers forum and they answered I should use picker.presentationController.delegate
So I took code from you library and modified it this way:

`
    val pickerResults: List<PHPickerResult> = suspendCoroutine { continuation ->
        // Create a picker delegate
        val phPickerDelegate = PhPickerDelegate(
            onFilesPicked = continuation::resume
        )
        val phPickerDismissDelegate = PhPickerDismissDelegate(
            onFilesPicked = continuation::resume
        )
`

As you see I added 
`
 val phPickerDismissDelegate = PhPickerDismissDelegate(
`

than I modified this part:

`
        val controller = PHPickerViewController(configuration = configuration)
        controller.delegate = phPickerDelegate
        controller.presentationController?.delegate = phPickerDismissDelegate
`

And also this is the delegate code:

`
internal class PhPickerDismissDelegate(
    private val onFilesPicked: (List<PHPickerResult>) -> Unit
) : NSObject(),
    UIAdaptivePresentationControllerDelegateProtocol {
        override fun presentationControllerDidDismiss(presentationController: UIPresentationController) {
            Napier.i(tag = "Picker worked", message = "Picker dismissed")
            onFilesPicked(listOf())
        }
}
`

And I had INFO Picker worked - Picker dismissed - text in my log.

**Comment by vinceglb** [comment]
Thank you! Your suggestions are very helpful! I'm going to push a fix soon 👌
