### ISSUE TITLE
Crash on selecting file in iOS

### ISSUE THREAD

**Issue by derynia** [vinceglb/FileKit#128]
I used version 0.7.0 and everything worked fine.
I went to version 0.8.3
And now on selecting a file on iOS I get crash:
024-10-04 16:58:57.641203+0200 NextShip[16017:442712] [default] [ERROR] Could not create a bookmark: NSError: Cocoa 4097 "connection to service named com.apple.FileProvider"
Uncaught Kotlin exception: kotlin.native.internal.IrLinkageError: Property accessor 'pathComponents.<get-pathComponents>' can not be called: No property accessor found for symbol 'platform.Foundation/NSURL.pathComponents.<get-pathComponents>|objc:pathComponents#Accessor[100]'
    at 0   NextShip.debug.dylib                0x10e886ba7        kfun:kotlin.Throwable#<init>(kotlin.String?){} + 119 
    at 1   NextShip.debug.dylib                0x10e87ffcb        kfun:kotlin.Error#<init>(kotlin.String?){} + 115 
    at 2   NextShip.debug.dylib                0x10e8bdda7        kfun:kotlin.native.internal.IrLinkageError#<init>(kotlin.String?){} + 115 
    at 3   NextShip.debug.dylib                0x10e8bde5f        kfun:kotlin.native.internal#ThrowIrLinkageError(kotlin.String?){}kotlin.Nothing + 163 
    at 4   NextShip.debug.dylib                0x1106322bb        kfun:io.github.vinceglb.filekit.core.FileKit.callPhPicker$lambda$5$lambda$4#internal + 559 
    at 5   NextShip.debug.dylib                0x110633fc7        kfun:io.github.vinceglb.filekit.core.FileKit.$callPhPicker$lambda$5$lambda$4$FUNCTION_REFERENCE$7.invoke#internal + 131 
    at 6   NextShip.debug.dylib                0x1106340fb        kfun:io.github.vinceglb.filekit.core.FileKit.$callPhPicker$lambda$5$lambda$4$FUNCTION_REFERENCE$7.$<bridge-UNNNN>invoke(platform.Foundation.NSURL?;platform.Foundation.NSError?){}#internal + 127 
    at 7   NextShip.debug.dylib                0x10e9cb677        kfun:kotlin.Function2#invoke(1:0;1:1){}1:2-trampoline + 115 
    at 8   NextShip.debug.dylib                0x11063445b        _46696c654b69743a66696c656b69742d636f72652f55736572732f72756e6e65722f776f726b2f46696c654b69742f46696c654b69742f66696c656b69742d636f72652f7372632f696f734d61696e2f6b6f746c696e2f696f2f6769746875622f76696e6365676c622f66696c656b69742f636f72652f46696c654b69742e696f732e6b74_knbridge90 + 231 
    at 9   PhotosUI                            0x1ac2112bb        -[PUPhotosFileProviderItemProvider _completeProgressWithUUID:success:completionHandler:] + 375 
    at 10  PhotosUI                            0x1ac211f27        __94-[PUPhotosFileProviderItemProvider loadFileRepresentationForTypeIdentifier:completionHandler:]_block_invoke_2 + 163 
    at 11  Foundation                          0x180f20adb        __76-[NSItemProvider loadFileRepresentationForTypeIdentifier:completionHandler:]_block_invoke_4 + 187 
    at 12  libdispatch.dylib                   0x1801774eb        _dispatch_call_block_and_release + 23 
    at 13  libdispatch.dylib                   0x180178ddf        _dispatch_client_callout + 15 
    at 14  libdispatch.dylib                   0x180180f5f        _dispatch_lane_serial_drain + 955 
    at 15  libdispatch.dylib                   0x180181a97        _dispatch_lane_invoke + 387 
    at 16  libdispatch.dylib                   0x18018cf43        _dispatch_root_queue_drain_deferred_wlh + 275 
    at 17  libdispatch.dylib                   0x18018c59f        _dispatch_workloop_worker_thread + 439 
    at 18  libsystem_pthread.dylib             0x1049cfb73        _pthread_wqthread + 283 
    at 19  libsystem_pthread.dylib             0x1049ce933        start_wqthread + 7 

This warning 
2024-10-04 17:02:00.986096+0200 NextShip[16333:449104] [default] [ERROR] Could not create a bookmark: NSError: Cocoa 4097 "connection to service named com.apple.FileProvider"

I had earlier. But there was no crash and all worked fine.

**Comment by vinceglb** [comment]
Hi @derynia! Thanks for reporting this issue.

Since 0.8.2, FileKit supports only Kotlin 2.0.20 and above. See more here: https://github.com/vinceglb/FileKit/issues/105#issuecomment-2336483721

What version of Kotlin are you using?

**Comment by derynia** [comment]
> Since 0.8.2, FileKit supports only Kotlin 2.0.20 and above. See more here: [#105 (comment)]

Thanks it helped. I didn't switch to Kotlin 2.0.20 in my project as I use Realm and it was not supported in 2.0.20.
Now it's supported so I tried 0.8.3 of you library and it works fine.

**Comment by vinceglb** [comment]
Perfect 👌
