### ISSUE TITLE
`path` messed up on Linux in newest release

### ISSUE THREAD

**Issue by thornySoap** [vinceglb/FileKit#132]
Hello! The `path` on Linux (Debian 13 testing) looks like `"path/to/executable/file:/path/to/actual/file"` in the newest release `0.8.4`. In the previous release this doesn't happen. This also leads to for example `readBytes`to fail.

**Comment by vinceglb** [comment]
Hi! Thanks for reporting this! Sorry for the regression 😅 I'm going to take a look

**Comment by vinceglb** [comment]
Does version 0.8.5 fix the problem?

**Comment by thornySoap** [comment]
Now the `pickFile` function throws an exception before completion:
```
Exception in thread "AWT-EventQueue-0 @coroutine#184" java.lang.IllegalArgumentException: URI is not absolute
	at java.base/java.io.File.<init>(File.java:418)
	at io.github.vinceglb.filekit.core.platform.xdg.XdgFilePickerPortal.pickFiles(XdgFilePickerPortal.kt:116)
	at io.github.vinceglb.filekit.core.platform.xdg.XdgFilePickerPortal.access$pickFiles(XdgFilePickerPortal.kt:29)
	at io.github.vinceglb.filekit.core.platform.xdg.XdgFilePickerPortal$pickFiles$2.invokeSuspend(XdgFilePickerPortal.kt)
```
I intercepted the URI using the debugger and it looked like this `"file%3A%2F%2F%2Fhome%2Fuser%2FDownloads%2Fdirectory%2Ffile.txt"`. I don't know how it looks in the other versions but maybe something is off with the encoding?

**Comment by vinceglb** [comment]
Thank you for your suggestion. I added the scheme in the tests. 

When receiving the URI string, I removed the scheme part and encoded the rest. Then I created the URI from the encoded rest without the scheme. It's working in the tests, but I haven't a Linux to test it on my own.

I created version 0.8.6. I hope it's fixed now!

**Comment by thornySoap** [comment]
Hm, I still got the same error message. I think maybe the scheme in `val (_, rest) = splitUrl(this)` shouldn't be discarded but like after url encryption of the path added again because this is what I think where the exception is thrown:

![Screenshot 2024-10-06 16:11:59](https://github.com/user-attachments/assets/bb0d5ed1-c743-4654-a602-8784f82532f4)

![Screenshot 2024-10-06 16:12:25](https://github.com/user-attachments/assets/b2b546cb-4186-4c44-8eff-4d9ea9ef8425)

Really hope I don't mislead you in some way :worried:, but I think it should work after that. I feel a bit bad already to cause all these new releases 😅

**Comment by vinceglb** [comment]
No problem, it's my bad at the end. I downloaded an Ubuntu VM this time to test my changes. 

Version 0.8.7 is out, it should be good now 😂🤞

**Comment by thornySoap** [comment]
It's resolved for me now, thank you!
