### ISSUE TITLE
is it possible to save the platformFile path to disk and use it to get the file again?

### ISSUE THREAD

**Issue by BitByAVampire** [vinceglb/FileKit#149]
After user has selected the images or videos to give to the app, is it possible to save that path to get the media again on app relaunch? I tried using Coil to load the uri stored but it did not seem to work.

**Comment by santiwanti** [comment]
Have you tried storing the path in something like SharedPreferences and then reopening that path using FileKit?

**Comment by BitByAVampire** [comment]
How to reopen using filekit?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by BitByAVampire** [comment]
I was able to achieve this on ios using coil's AsyncImage but on Android...

**Comment by vinceglb** [comment]
We are working on the next version of FileKit. 

In this next version, it will possible to easily pick a file then cache it in the internal memory of the application to use this file later. Like this, you can pick a photo, cache it in the app and then retrieve it when you want later.

Here an example of picking then caching image path in your database:

```kt
@OptIn(ExperimentalUuidApi::class)
suspend fun pickAndSaveImageLocally(): PlatformFile? {
    // Pick a file
    val file = FileKit.pickFile(type = PickerType.Image)

    // If file is not null, write it to the app's files directory
    return file?.let {
        // Create a new file in the app's files directory
        val appFile = FileKit.filesDir / "image-${Uuid.random()}.${it.extension}"

        // Write the picked file to the new file
        appFile.write(file)

        // Save the file path in your database
        // Replace this by your database logic
        yourDatabase.putString("myImage", appFile.path.toString())

        // Return the new local file
        appFile
    }
}

fun retrieveFileFromDatabase(): PlatformFile? {
    // Retrieve the file path from your database
    // Replace this by your database logic
    return yourDatabase.getString("myImage")?.let {
        // Create a Path from the file path
        val filePath = Path(it)

        // Return the file
        PlatformFile(filePath)
    }
}

@Composable
fun DisplayYourImage(image: PlatformFile) {
    AsyncImage(
        model = image.coilModel,
        contentDescription = image.name,
        contentScale = ContentScale.Crop,
        modifier = Modifier
            .fillMaxSize()
    )
}
```

It's possible right now to try the new version of FileKit. Here how to do this. 

In your settings.gradle.kts

```kt
dependencyResolutionManagement {
    repositories {
        // ...
        maven("https://s01.oss.sonatype.org/content/repositories/snapshots/") // Add this line
    }
}
```

In your build.gradle.kts, import FileKit like this:

```kt
implementation("io.github.vinceglb:filekit-dialog-compose:0.10.0-SNAPSHOT")
implementation("io.github.vinceglb:filekit-coil:0.10.0-SNAPSHOT")
```

Now, you can adapt the example code above to pick then cache your images like you want. Also, to display a platformFile with Coil, you can just use the extension `platformFile.coilModel` like in the example.

Don't hesitate if you have any questions.

**Comment by BitByAVampire** [comment]
Yes, thank you, my question was not actually about saving the image itself but just the path. It seems on ios the filekit is returning the actual uri but on android it is returning just the path path (I get the uri and path confused). I tried prepending "content://" and "file://" to the path when calling AsyncImage but it did not work.

**Comment by vinceglb** [comment]
Here is the Android documentation about the Photo Picker:

https://developer.android.com/training/data-storage/shared/photopicker#persist-media-file-access

Like you can see, the Uri is available only for the current session. When the app is stopped, you lose the access to the file. 

The best imo is to copy the photo in the storage of your application.

**Comment by vinceglb** [comment]
@BitByAVampire, here is settings.gradle.kts file that is working:

```kt
rootProject.name = "MyApp"
enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

pluginManagement {
    repositories {
        google {
            mavenContent {
                includeGroupAndSubgroups("androidx")
                includeGroupAndSubgroups("com.android")
                includeGroupAndSubgroups("com.google")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositories {
        google {
            mavenContent {
                includeGroupAndSubgroups("androidx")
                includeGroupAndSubgroups("com.android")
                includeGroupAndSubgroups("com.google")
            }
        }
        mavenCentral()
        maven("https://s01.oss.sonatype.org/content/repositories/snapshots/")   // add this
    }
}

include(":composeApp")
```
