### ISSUE TITLE
IOS: Uncaught Kotlin exception: kotlin.native.internal.IrLinkageError

### ISSUE THREAD

**Issue by Vaxela** [vinceglb/FileKit#151]
Hello i want to use your package, in android work well but in ios  i have an error when i try to pick a file :/ 
kotlinVersion = "1.9.23"
filekit = "0.8.7"

i saw other issue with people maybe my kotlin version to old ? 

Compliqueted to upgrade using other library not compatible with 2.0... 

So i have downgrade to 0.8.1 working on iOS but complicated because we can't have the new update alala ^^

Can you help me ? Thank you :D 

```
Uncaught Kotlin exception: kotlin.native.internal.IrLinkageError: Property accessor 'pathComponents.<get-pathComponents>' can not be called: No property accessor found for symbol 'platform.Foundation/NSURL.pathComponents.<get-pathComponents>|objc:pathComponents#Accessor[100]'
    at 0   EasyScan Dev Debug                  0x100eae07f        kfun:kotlin.Throwable#<init>(kotlin.String?){} + 119 
    at 1   EasyScan Dev Debug                  0x100ea73ef        kfun:kotlin.Error#<init>(kotlin.String?){} + 115 
    at 2   EasyScan Dev Debug                  0x100ee0c63        kfun:kotlin.native.internal.IrLinkageError#<init>(kotlin.String?){} + 115 
    at 3   EasyScan Dev Debug                  0x100ee0d1b        kfun:kotlin.native.internal#ThrowIrLinkageError(kotlin.String?){}kotlin.Nothing + 163 
    at 4   EasyScan Dev Debug                  0x102609547        kfun:io.github.vinceglb.filekit.core.FileKit.callPhPicker$lambda$8$lambda$7$lambda$6#internal + 559 
    at 5   EasyScan Dev Debug                  0x10260d0ab        kfun:io.github.vinceglb.filekit.core.FileKit.$callPhPicker$lambda$8$lambda$7$lambda$6$FUNCTION_REFERENCE$8.invoke#internal + 131 
    at 6   EasyScan Dev Debug                  0x10260d1df        kfun:io.github.vinceglb.filekit.core.FileKit.$callPhPicker$lambda$8$lambda$7$lambda$6$FUNCTION_REFERENCE$8.$<bridge-UNNNN>invoke(platform.Foundation.NSURL?;platform.Foundation.NSError?){}#internal + 127 
    at 7   EasyScan Dev Debug                  0x100fe435b        kfun:kotlin.Function2#invoke(1:0;1:1){}1:2-trampoline + 115 
    at 8   EasyScan Dev Debug                  0x10260d9cb        _46696c654b69743a66696c656b69742d636f72652f55736572732f72756e6e65722f776f726b2f46696c654b69742f46696c654b69742f66696c656b69742d636f72652f7372632f696f734d61696e2f6b6f746c696e2f696f2f6769746875622f76696e6365676c622f66696c656b69742f636f72652f46696c654b69742e696f732e6b74_knbridge61 + 231 
    at 9   PhotosUI                            0x2319e114b        <redacted> + 383 
    at 10  PhotosUI                            0x2319e208f        <redacted> + 191 
    at 11  Foundation                          0x19f7b7a4f        <redacted> + 175 
    at 12  libdispatch.dylib                   0x1066e4a2f        _dispatch_call_block_and_release + 31 
    at 13  libdispatch.dylib                   0x1066e671b        _dispatch_client_callout + 19 
    at 14  libdispatch.dylib                   0x1066ee5e7        _dispatch_lane_serial_drain + 827 
    at 15  libdispatch.dylib                   0x1066ef35f        _dispatch_lane_invoke + 407 
    at 16  libdispatch.dylib                   0x1066fc5ef        _dispatch_root_queue_drain_deferred_wlh + 327 
    at 17  libdispatch.dylib                   0x1066fbbff        _dispatch_workloop_worker_thread + 579 
    at 18  libsystem_pthread.dylib             0x2276cfc7b        _pthread_wqthread + 287 
    at 19  libsystem_pthread.dylib             0x2276cc487        start_wqthread + 7 
```

That my base viewmodel with FileKit core : 
```kt
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import co.touchlab.kermit.Logger
import io.github.vinceglb.filekit.core.FileKit
import io.github.vinceglb.filekit.core.PickerMode
import io.github.vinceglb.filekit.core.PickerType
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch

class ImportVideoOptionViewModel : ViewModel() {
    private val _uiState = MutableStateFlow(ImportVideoUiState(false))
    val uiState: StateFlow<ImportVideoUiState> = _uiState

    fun pickImage() = executeWithLoading {

        // Pick a file
        val file = FileKit.pickFile(
            type = PickerType.Video,
            title = null,
            mode = PickerMode.Single,
            initialDirectory = null,
            platformSettings = null,
        )

        // Add file to the state
        if (file != null) {
            Logger.d("File picked: $file")
        }
    }



    private fun executeWithLoading(block: suspend () -> Unit) {
        viewModelScope.launch {
            _uiState.update { it.copy(loading = true) }
            block()
            _uiState.update { it.copy(loading = false) }
        }
    }
}
```

**Comment by Vaxela** [comment]
up i downgrade to 0.8.1 that work but it will be hard to upgrade all the project to 2.0.20 ^^

**Comment by Vaxela** [comment]
I hade the problem with the path :/ fix in other version ^^

**Comment by vinceglb** [comment]
Yes, the crash is caused by incompatibilities between Kotlin 2.0.20 and before:
- https://github.com/vinceglb/FileKit/issues/105
- https://github.com/vinceglb/FileKit/issues/104

From our side, there is no easy / maintainable way to fix this issue. To support older versions of Kotlin, one possible solution  is to fork the project, change the version of Kotlin and adapt the code. After that, it will be required to cherry-pick all the new commits from the main project to this fork.

From your side, what are the libraries that do not support Kotlin 2.0.20? 
Also, what do you mean by "having a problem with the path"? Do you reference that issue: https://github.com/vinceglb/FileKit/issues/118?

**Comment by Vaxela** [comment]
I need to verify and upgrade because it's a business application so i can't upgrade it like that ^^
Yes that was fix after :) https://github.com/vinceglb/FileKit/issues/118

**Comment by Vaxela** [comment]
Hello i also tried to upgrade to kotlin 2.0.20 everything was working fine except in IOS they add a new behaviour for UIkitView interaction https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-ios-touch.html and my MkMapView map can't work for the moment :/

**Comment by Vaxela** [comment]
ok so i've directly added the FileKitCore library in the project from github from main branch and that work in 1.9.25 but i wan't to copy the file with the path to the app internal directory and i have a file not found  from java.io.FileNotFoundException: /data/user/0/com.syslor.easyscan.dev.debug/files/1000000733.mp4: open failed: ENOENT (No such file or directory)
2024-11-05 11:20:25.521  4583-4583  <no-tag>                com.syslor.easyscan.dev.debug        D  File not copied

actual suspend fun copyFile(sourcePath: String, destinationPath: String): Boolean {
    return try {
        val inputFile = File(sourcePath)
        val outputFile = File(destinationPath)

        FileInputStream(inputFile).use { input ->
            FileOutputStream(outputFile).use { output ->
                input.copyTo(output, bufferSize = 1024 * 8) // 8 KB buffer
            }
        }
        true
    } catch (e: IOException) {
        e.printStackTrace()
        false
    }
}

**Comment by vinceglb** [comment]
Perfecto 🎉
