### ISSUE TITLE
Js target is missing for filekit-compose

### ISSUE THREAD

**Issue by hondogo** [vinceglb/FileKit#47]
Js target is missing for filekit-compose.

https://github.com/vinceglb/FileKit/blob/main/filekit-compose/build.gradle.kts

**Comment by vinceglb** [comment]
Thanks for reporting this! I'll add it and push a new version

**Comment by vinceglb** [comment]
@hondogo It seems like it is not possible to create Compose Multiplatform apps targeting Js. I didn't find any documentation about this.

Do you use Compose Multiplatform with Js target? If yes, can you send me a Compose Multiplatform example project using Js target, Kotlin 2.0 and compose version 1.6.11? Thanks!

**Comment by hondogo** [comment]
Hello, @vinceglb ! I've made pull request implementing JS target for compose, but I don't have access rights to push it here. Can you give me rights to push pull request?

**Comment by santiwanti** [comment]
@hondogo the usual process to submit pull requests is to fork the project and submit the pull request to your fork which will by default create a pull request to the original project as well. You shouldn't need any permissions to do this.

**Comment by hondogo** [comment]
https://github.com/vinceglb/FileKit/pull/61
