### ISSUE TITLE
Android Preview does not function

### ISSUE THREAD

**Issue by griffinsorrentino** [vinceglb/FileKit#51]
When using `rememberFilePickerLauncher`, the previewer in the `androidMain` source set stops functioning because of a `ClassCastException`. During preview rendering, the `LocalContext.current` returns a mocked `BridgeContext` and not a `ComponentActivity`

<details>
<summary>Stack Trace</summary>

`java.lang.ClassCastException: class com.android.layoutlib.bridge.android.BridgeContext cannot be cast to class androidx.activity.ComponentActivity (com.android.layoutlib.bridge.android.BridgeContext is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @5b4286a7; androidx.activity.ComponentActivity is in unnamed module of loader org.jetbrains.android.uipreview.StudioModuleClassLoader @57ee5812)   at io.github.vinceglb.filekit.compose.FileKitCompose_androidKt.InitFileKit(FileKitCompose.android.kt:11)   at io.github.vinceglb.filekit.compose.FileKitComposeKt.rememberFilePickerLauncher(FileKitCompose.kt:26)`
</details>

**Comment by griffinsorrentino** [comment]
@vinceglb Are you by chance able to take a look into this issue and the PR?

**Comment by vinceglb** [comment]
Thank you @griffinsorrentino for reporting this and your PR! I'm going to create a new version with your changes today
