### ISSUE TITLE
Please provide file-stream

### ISSUE THREAD

**Issue by kagg886** [vinceglb/FileKit#54]
in my views, if we call `readBytes()` from a large file, this can cause oom

please support it, thks :D

**Comment by vinceglb** [comment]
Thanks for creating this issue! It's definitively a good idea, we'll probably add this feature. But I didn't have time to work on this feature shortly.

If you still need it quickly, it's possible to implement your custom code easily. `PlatformFile` lets you access the underling file on each platform. This means you can create an expect function and implement the file stream on each platform you are using.
