### ISSUE TITLE
Ios video picker error

### ISSUE THREAD

**Issue by the-best-is-best** [vinceglb/FileKit#55]
No appropriate representation found for type public.video

**Comment by cpienovidlabs** [comment]
I'm also experiencing this. I'm using an iPhone 13 with iOS 17.5.1
Someone here mentioned it could be happening to WhatsApp videos but that's not true https://forums.developer.apple.com/forums/thread/740438?answerId=46144025#46144025

**Comment by the-best-is-best** [comment]
This problem in this library uses old Api
But don't related to ur issue

**Comment by the-best-is-best** [comment]
I will upload a new library soon

**Comment by the-best-is-best** [comment]
thank you i will close this issue
